language: python
stages:
  - name: update
    if: branch = master AND type = push

jobs:
  include:
    - name: Update index
      stage: update
      script:
        - python ./scripts/update-index.py
